// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"NewProject/app/biz"
	"NewProject/app/data"
	"NewProject/app/router"
	"NewProject/app/service"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

func InitApp() *gin.Engine {
	dataData := data.NewData()
	userData := data.NewUserData(dataData)
	userBiz := biz.NewUserBiz(userData)
	userService := service.NewUserService(userBiz)
	resourceData := data.NewResourceData(dataData)
	resourceBiz := biz.NewResourceBiz(resourceData)
	resourceService := service.NewResourceService(resourceBiz)
	roleData := data.NewRoleData(dataData)
	roleBiz := biz.NewRoleBiz(roleData)
	roleService := service.NewRoleService(roleBiz)
	roleResourceData := data.NewRoleResourceData(dataData)
	roleResourceBiz := biz.NewRoleResourceBiz(roleResourceData)
	roleResourceService := service.NewRoleResourceService(roleResourceBiz)
	userRoleData := data.NewRoleUserData(dataData)
	userRoleBiz := biz.NewUserRoleBiz(userRoleData)
	userRoleService := service.NewUserRoleService(userRoleBiz)
	app := &router.App{
		UserService:         userService,
		ResourceService:     resourceService,
		RoleService:         roleService,
		RoleResourceService: roleResourceService,
		UserRoleService:     userRoleService,
	}
	engine := router.InitGenEngine(app)
	return engine
}
